package Assigment_3_OOP;

import java.awt.*;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import java.util.HashMap;
import java.util.Map;

public class Platform {
    int x, y, width, height;
    int screenHeight;
    boolean isSolid = true;

    // Updated by Main whenever the level changes: 0=city 1=desert 2=forest 3=volcano
    public static int currentWorld = 0;

    // Transparent, cropped sprites (generated by preprocessing script)
    private static final Map<Integer, BufferedImage> sprites = new HashMap<>();
    private static final String[] SPRITE_FILES = {
        "platform_city_t.png",
        "platform_desert_t.png",
        "platform_forest_t.png",
        "platform_volcano_t.png"
    };

    // Solid colour used as the platform body underneath the sprite
    private static final Color[] BODY_COLORS = {
        new Color(60,  40,  20),   // city  – brown earth
        new Color(150, 100, 40),   // desert – sandy
        new Color(30,  80,  20),   // forest – dark green
        new Color(80,  20,  10)    // volcano – dark rock
    };

    static {
        for (int i = 0; i < SPRITE_FILES.length; i++) {
            try {
                sprites.put(i, ImageIO.read(
                    Platform.class.getResourceAsStream(SPRITE_FILES[i])));
            } catch (Exception e) {
                sprites.put(i, null);
            }
        }
    }

    public Platform(int x, int y, int width, int height) {
        this(x, y, width, height, true);
    }
    public Platform(int x, int y, int width, int height, boolean isSolid) {
        this.x = x; this.y = y; this.width = width;
        this.height = height; this.isSolid = isSolid;
    }
    public void setScreenHeight(int sh) { this.screenHeight = sh; }

    public void draw(Graphics g) {
        int drawY = screenHeight - y - height;   // top-left Y in screen coords
        Graphics2D g2 = (Graphics2D) g;
        int w = Math.min(currentWorld, 3);
        BufferedImage spr = sprites.get(w);

        // ── Visual height = 80% of collision height so the platform looks
        //    20% thinner without affecting the collision box (p.y / p.height).
        //    The top surface (drawY) stays fixed — only the bottom shrinks up.
        int visH = (int)(height * 0.80);

        // ── 1. Fill the solid body of the platform ──────────────────────────
        g2.setColor(BODY_COLORS[w]);
        g2.fillRect(x, drawY, width, visH);

        // ── 2. Tile the sprite image across the top of the platform ─────────
        //    The sprite is drawn anchored to drawY (top of platform rect).
        //    Its height extends DOWN from the platform top edge (decoration hangs down).
        //    We tile it horizontally.
        if (spr != null) {
            int imgW = spr.getWidth();
            int imgH = spr.getHeight();

            // Scale sprite height to match the platform's height, but cap so it
            // doesn't look distorted — we preserve aspect ratio and let it overhang.
            // The drawn height = min(platform height, sprite natural height scaled to platform width)
            int drawSprH = imgH; // draw at natural height; hangs below platform if needed

            Shape oldClip = g2.getClip();
            // Clip to the visual height (80%) so hanging bits stay within the
            // slimmer body — allow a little extra below for dripping decoration
            g2.setClip(x, drawY, width, visH + Math.min(imgH, visH));

            for (int tx = x; tx < x + width; tx += imgW) {
                g2.drawImage(spr, tx, drawY, tx + imgW, drawY + drawSprH,
                             0, 0, imgW, imgH, null);
            }
            g2.setClip(oldClip);
        }
    }
}
